### Insertar producto 1
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description for product 1",
  "price": 19.99
}

### Insertar producto 2
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Product 2",
  "description": "Description for product 2",
  "price": 29.99
}

### Insertar producto 3
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Product 3",
  "description": "Description for product 3",
  "price": 39.99
}





###
GET http://localhost:8080/api/products

